### PR TITLE
Bug (#15) sprintf breaks tests when a matching strings contains '%'

### LINKED ISSUE #15: ErrorException : sprintf(): Too few arguments
```bash
ErrorException : sprintf(): Too few arguments
.../vendor/nunomaduro/laravel-mojito/src/ViewAssertion.php:168
.../vendor/nunomaduro/laravel-mojito/src/ViewAssertion.php:99
```

I encountered this error when doing a `contains` where the expected text has a percentage (%) symbol and does not exist in the html provided. See below test that replicates this issue and currently fails but will pass when the issue has been fixed.

```php
public function testPercentageEscaped()
{
    try {
        (new ViewAssertion('<div>This is a test</div>'))
            ->contains('This text has a percentage 43% symbol');

        $this->assertTrue(false, 'Expected assertion error was not thrown.');
    } catch (AssertionFailedError $e) {
        $this->assertSame(
            "Failed asserting that the text `This text has a percentage 43% symbol` exists within `<div>This is a test</div>`.",
            $e->getMessage()
        );
    }
}
```

One solution would be to add this `str_replace` line to the `contains` method which will escape any percentage symbols. Although it might be better to stop using `sprintf` in `ViewAssertion::assert`:

```php
public function contains(string $text): ViewAssertion
{
    $escaped = str_replace('%', '%%', $text);
    self::assert(function () use ($text) {
        Assert::assertStringContainsString((string) $text, $this->html);
    }, "Failed asserting that the text `$escaped` exists within %s.");

    return $this;
}
```

### PR DESCRIPTION
**Pull request by SimoTod**
Closes #15
As suggested in that thread I removed `sprintf` in favour of string interpolation.
The performance impact, if existing, is negligible and this version is easier to read.
I've added some test to make sure that the message format didn't change plus one test to address this specific bug in a miscellanea class.
Since ViewAssertion::assert is private, it's safe and not a breaking change.

For some reasons, I didn't get a notification for this and the other ticket. I believe it was because I hadn't clicked 'watch'. It's sorted now, I should get the alert next time, thanks for the heads up.

### CODE REVIEW

**Review by nunomaduro — DISMISSED** [review]
Thanks for this work. We just need to understand why tests are failing.

**Comment by SimoTod** [comment]
The last version passed the previous was failing in php 7.2. For some reason one of the selectors was also returning a newline after the tag but only in php 7.2 and since I printed the full message, it was failing the comparison. I can have a look and see if it makes sense to trim the selected html later/tomorrow.

File: tests/Misc.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+namespace Tests;
+
+use NunoMaduro\LaravelMojito\InteractsWithViews;
+use PHPUnit\Framework\AssertionFailedError;
+use PHPUnit\Framework\TestCase;
+
+/**
+ * @internal
+ */
+final class Misc extends TestCase
```
Comment (nunomaduro) [inline tests/Misc.php]: Can we improve the name of this class?

Comment (SimoTod) [reply tests/Misc.php]: No problem. I moved that test into an existing class.
To be fair, it can't also be removed. I added just to make sure I could replicate and fix the issue but, now that we don't use sprintf anymore, % is a normal character like many others so it doesn't make much sense to test it in the future.
My plan was to take it out again once we are happy with the feature.

**Review by nunomaduro — DISMISSED** [review]
Perfect! Thanks!

File: src/ViewAssertion.php [hunk 2]
```diff
@@ -136,7 +136,7 @@ public function has(string $selector): ViewAssertion
     {
         self::assert(function () use ($selector) {
             Assert::assertThat($this->crawler, new CrawlerSelectorExists($selector));
-        }, "Failed asserting that `$selector` exists within %s.");
+        }, "Failed asserting that `{$selector}` exists within `{$this->html}`.");
```
Comment (dmason30) [inline src/ViewAssertion.php]: @SimoTod I would argue that `self::assert` is now kind of redundant as you can pass the custom message directly to the assertion method: 

```php
Assert::assertThat(
    $this->crawler,
    new CrawlerSelectorExists($selector), 
    "Failed asserting that `{$selector}` exists within `{$this->html}`."
);
```

And the same in the other assertion methods.

Comment (SimoTod) [reply src/ViewAssertion.php]: @dmason30 
I agree that it's redundant but I don't think we can remove it as part of this patch. 
Despite being private, the ViewAssertion class is 'Macroable' which means that users can add methods at runtime and, in their macro, they can potentially use self::assert.

If I removed that function, all people's macro using it would suddenly break while now the worst thing that could happen is that someone was using %s and it won't replace the placeholder on failure but everything will still be working as expected.

We can mark is as deprecated and remove it when we tag a major release I suppose.

Comment (dmason30) [reply src/ViewAssertion.php]: Fair point, seems like an appropriate process. However, having a version < 1 (currently 0.2.4) is usually classed as still in beta and breaking patches is allowed. 😉 

I would say that you could still change all the existing assert methods so that it is no longer being used internally and then you could keep `self::assert` as before with the `sprintf`, then  `@deprecate` it and remove in the next major. 

Feel free to ignore the above if you are happy with how it currently is!

Note that the phpunit assertion methods throw child classes of `AssertionFailedException`. For example, `Assert::that` will throw an `ExpectationException` which extends `AssertionFailedException`.

Comment (SimoTod) [reply src/ViewAssertion.php]: Yeah, that would work, I'll push an update later on.

It's just that I get really annoyed when I'm on the other side and things break when I run composer update. 😂

**Comment by SimoTod** [comment]
@nunomaduro I made a couple of changes as a follow up for the conversation I had with Daniel.
If you are happy with this PR i can tag a release.

**Review by nunomaduro — APPROVED** [review]
Good job. 

Nice move on the private method.
